---
apiVersion: ivory-operator.ivorysql.org/v1beta1
kind: IvoryCluster
metadata:
  name: switchover
status:
  instances:
    - name: "00"
      replicas: 2
      readyReplicas: 2
      updatedReplicas: 2
---
# Patroni labels and readiness happen separately.
# The next step expects to find pods by their role label; wait for them here.
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: switchover
    ivory-operator.ivorysql.org/role: primary
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: switchover
    ivory-operator.ivorysql.org/role: replica
