apiVersion: ivory-operator.ivorysql.org/v1beta1
kind: IvoryCluster
metadata:
  name: init-pgbackrest
status:
  instances:
  - name: instance1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
  pgbackrest:
    repoHost:
      apiVersion: apps/v1
      kind: StatefulSet
      ready: true
    repos:
# Assert that the status has the two repos, with only the first having the `replicaCreateBackupComplete` field
    - bound: true
      name: repo1
      replicaCreateBackupComplete: true
      stanzaCreated: true
    - bound: true
      name: repo2
      stanzaCreated: true
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    ivory-operator.ivorysql.org/cluster: init-pgbackrest
    ivory-operator.ivorysql.org/pgbackrest-backup: replica-create
    ivory-operator.ivorysql.org/pgbackrest-repo: repo1
status:
  succeeded: 1
